# Generated by Django 3.2.9 on 2021-11-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='users',
        ),
    ]
