# Generated by Django 3.2.9 on 2021-12-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvotemodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_upvote', to='blog.postmodel'),
        ),
    ]
