# Generated by Django 3.2.9 on 2021-12-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
        ('action', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='blog.postmodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='subpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpost_comment', to='blog.postmodel'),
        ),
        migrations.AlterField(
            model_name='upvotemodel',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_upvote', to='blog.postmodel'),
        ),
        migrations.AlterField(
            model_name='upvotemodel',
            name='subpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpost_upvote', to='blog.postmodel'),
        ),
    ]
